version: '3.8'

services:
  app:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    container_name: face_app
    ports:
      - "8000:8000"
    volumes:
      - media_volume:/app/media
    environment:
      - DB_ENGINE=django.db.backends.mysql
      - DB_NAME=absen
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: face_db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=absen
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345
    ports:
      - "3000:3306"  # Map port host 3000 ke port MySQL default 3306 di container
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  media_volume:
  db_volume:

networks:
  app_network:
    driver: bridge