# Generated by Django 5.0.6 on 2025-03-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('jabatan', models.CharField(max_length=100)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='faces/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
