# Generated by Django 5.0.6 on 2025-03-28 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAbsen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kehadiran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('gambarKehadiran', models.ImageField(upload_to='attendance/')),
                ('namaAnggota', models.CharField(max_length=100)),
            ],
        ),
    ]
