# Generated by Django 5.0.6 on 2025-04-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAbsen', '0002_kehadiran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gambar',
        ),
        migrations.AddField(
            model_name='person',
            name='gambar_0',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gambar_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='gambar_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='kehadiran',
            name='gambarKehadiran',
            field=models.ImageField(upload_to='kehadiran/'),
        ),
    ]
