# Generated by Django 5.0.6 on 2025-04-05 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiAbsen', '0004_remove_person_gambar_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gambar_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
